In [1]:
# Exploración de los datasets

In [2]:
# Imports
import pandas as pd
from datetime import timedelta

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
# Importamos ambas tablas
file_path = "/Users/jaimeteran/Documents/PYTHON/vacanze_romane/horarios.xlsx"
df_horarios = pd.read_excel(file_path)

file_path = "/Users/jaimeteran/Documents/PYTHON/vacanze_romane/trabajadores.xlsx"
df_trabajadores = pd.read_excel(file_path)

In [4]:
df_horarios.head()

   semana  dia      fecha  worker_id   entrada  duracion_turno
0       1    1 2024-08-05          0  18:00:00             8.0
1       1    1 2024-08-05          2  13:00:00             8.0
2       1    1 2024-08-05          3  12:30:00             8.0
3       1    1 2024-08-05          5  18:30:00             7.5
4       1    1 2024-08-05          8  12:30:00             9.0

In [5]:
df_trabajadores.head()

   id   nombre fecha_alta fecha_baja
0   0    Marco 2024-08-05        NaT
1   1   Milena 2024-08-05        NaT
2   2  Souheil 2024-08-05 2024-09-05
3   3  Violeta 2024-08-05 2024-08-29
4   4   Kantia 2024-08-05 2025-03-02

In [6]:
ultima_fecha_por_worker = (
    df_horarios
    .groupby('worker_id')['fecha']
    .max()
    .reset_index()
)

print(ultima_fecha_por_worker)

    worker_id      fecha
0           0 2026-05-24
1           1 2026-05-03
2           2 2024-09-05
3           3 2024-08-29
4           4 2025-03-02
5           5 2026-01-25
6           6 2025-08-24
7           7 2025-07-27
8           8 2026-05-03
9           9 2024-12-01
10         10 2024-09-08
11         11 2024-12-08
12         12 2025-08-24
13         13 2024-10-13
14         14 2025-11-02
15         15 2025-06-08
16         16 2025-12-21
17         17 2025-04-13
18         18 2026-05-24
19         19 2025-09-03
20         20 2025-09-07
21         21 2025-08-24
22         22 2026-05-24
23         23 2025-08-17
24         24 2026-05-24
25         25 2026-04-25
26         26 2026-04-12
27         27 2026-04-12
28         28 2026-05-24

In [7]:
df_trabajadores.head(50)

    id    nombre fecha_alta fecha_baja
0    0     Marco 2024-08-05        NaT
1    1    Milena 2024-08-05        NaT
2    2   Souheil 2024-08-05 2024-09-05
3    3   Violeta 2024-08-05 2024-08-29
4    4    Kantia 2024-08-05 2025-03-02
5    5     Elisa 2024-08-05 2026-01-25
6    6    Angela 2024-08-05 2025-08-24
7    7  Cristina 2024-08-05 2025-07-27
8    8     Jenny 2024-08-05        NaT
9    9     Lucia 2024-08-05 2024-12-01
10  10   Candela 2024-08-26 2024-09-08
11  11     Mihai 2024-09-02 2024-12-08
12  12   Arianna 2024-09-16 2025-08-24
13  13    Camilo 2024-09-30 2024-10-13
14  14   Daniele 2024-10-07 2025-11-02
15  15   Melissa 2024-11-15 2025-06-08
16  16      Sara 2025-01-13 2025-12-21
17  17    Andrea 2025-01-13 2025-04-13
18  18   Daniela 2025-04-07        NaT
19  19    Giulia 2025-06-09 2025-09-03
20  20    Adrian 2025-07-14 2025-09-07
21  21    Marina 2025-07-21 2025-08-24
22  22     Delia 2025-07-21        NaT
23  23    Aitana 2025-07-28 2025-08-17
24  24    Goreti 2025-09-01        NaT
25  25    Brenda 2026-03-09        NaT
26  26    Andres 2026-03-16 2026-04-12
27  27     Helen 2026-03-30 2026-04-12
28  28    Lamine 2026-05-18        NaT

Vemos la moda de los horarios

In [8]:
df_horarios = pd.read_excel("horarios.xlsx")

turnos = (
    df_horarios.groupby(
        ["entrada", "duracion_turno"]
    )
    .size()
    .reset_index(name="frecuencia")
    .sort_values(
        "frecuencia",
        ascending=False
    )
)

print(turnos.head(50))

      entrada  duracion_turno  frecuencia
13   12:30:00            8.50         181
25   13:30:00            8.00          92
1    11:25:00            9.08          76
68   15:30:00            8.50          74
46   15:00:00            6.00          70
103  17:00:00            7.00          68
94   16:30:00            7.50          66
113  17:30:00            6.50          63
116  17:30:00            8.00          60
11   12:00:00            9.00          60
5    11:55:00            9.08          56
81   16:00:00            8.00          55
69   15:30:00            9.00          53
58   15:25:00            8.58          49
109  17:25:00            6.58          49
122  18:00:00            6.00          46
126  18:00:00            8.00          45
98   16:55:00            7.08          43
45   14:55:00            9.08          41
52   15:00:00            9.00          37
134  18:30:00            7.50          36
12   12:30:00            8.00          34
21   13:25:00            8.08          33
105  17:00:00            8.00          28
14   12:30:00            9.00          25
33   14:00:00            7.50          23
50   15:00:00            8.00          22
87   16:25:00            7.58          20
60   15:25:00            9.08          20
48   15:00:00            7.00          19
74   15:55:00            8.08          18
72   15:30:00           10.50          18
90   16:25:00            9.08          18
125  18:00:00            7.50          18
83   16:00:00            9.00          18
117  17:30:00            8.50          15
95   16:30:00            8.00          14
67   15:30:00            8.00          14
97   16:30:00            9.00          13
119  17:55:00            6.08          12
128  18:25:00            5.58          12
32   14:00:00            7.00          11
17   13:00:00            8.00          11
133  18:30:00            7.00          10
114  17:30:00            7.00          10
85   16:00:00           10.00          10
24   13:30:00            7.50          10
28   13:55:00            7.58           9
63   15:30:00            6.00           8
106  17:00:00            8.50           8

In [9]:
df_horarios = pd.read_excel("horarios.xlsx")

# Asegurar formato datetime
df_horarios["entrada"] = pd.to_datetime(
    df_horarios["entrada"].astype(str),
    format="%H:%M:%S"
)

# Redondear a medias horas
df_horarios["entrada_norm"] = (
    df_horarios["entrada"]
    .dt.round("30min")
    .dt.strftime("%H:%M")
)

# Redondear duración a múltiplos de 0.5h
df_horarios["duracion_norm"] = (
    df_horarios["duracion_turno"] * 2
).round() / 2

turnos = (
    df_horarios
    .groupby(["entrada_norm", "duracion_norm"])
    .size()
    .reset_index(name="frecuencia")
    .sort_values("frecuencia", ascending=False)
)

print(turnos.head(50))

total_turnos = turnos["frecuencia"].sum()
print(f"Total turnos: {total_turnos}")

   entrada_norm  duracion_norm  frecuencia
11        12:30            8.5         181
18        13:30            8.0         125
47        15:30            8.5         123
8         12:00            9.0         116
76        17:30            6.5         112
70        17:00            7.0         111
64        16:30            7.5          86
37        15:00            9.0          78
3         11:30            9.0          76
48        15:30            9.0          74
31        15:00            6.0          74
56        16:00            8.0          73
79        17:30            8.0          67
82        18:00            6.0          59
86        18:00            8.0          45
92        18:30            7.5          36
10        12:30            8.0          34
23        14:00            7.5          32
67        16:30            9.0          31
72        17:00            8.0          31
12        12:30            9.0          25
35        15:00            8.0          23
85        18:00            7.5          20
46        15:30            8.0          20
33        15:00            7.0          20
58        16:00            9.0          19
51        15:30           10.5          18
89        18:30            5.5          18
65        16:30            8.0          17
80        17:30            8.5          15
22        14:00            7.0          15
73        17:00            8.5          14
77        17:30            7.0          13
14        13:00            8.0          12
17        13:30            7.5          11
60        16:00           10.0          10
91        18:30            7.0          10
50        15:30           10.0           8
42        15:30            6.0           8
84        18:00            7.0           7
43        15:30            6.5           7
36        15:00            8.5           6
57        16:00            8.5           6
2         11:30            6.0           6
45        15:30            7.5           6
32        15:00            6.5           6
66        16:30            8.5           6
90        18:30            6.0           5
95        19:00            7.0           5
26        14:00            9.5           5
Total turnos: 2023

In [10]:
print(turnos.shape[0])

96

In [11]:
top10 = turnos.head(10)["frecuencia"].sum()
top20 = turnos.head(20)["frecuencia"].sum()
total = turnos["frecuencia"].sum()

print("Top 10:", round(100*top10/total,2), "%")
print("Top 20:", round(100*top20/total,2), "%")

Top 10: 53.48 %
Top 20: 77.31 %

In [12]:
print(turnos.head(30))

turnos["acumulado"] = (
    turnos["frecuencia"]
    .cumsum()
    /
    turnos["frecuencia"].sum()
)

print(
    turnos[
        ["entrada_norm",
         "duracion_norm",
         "frecuencia",
         "acumulado"]
    ].head(30)
)

   entrada_norm  duracion_norm  frecuencia
11        12:30            8.5         181
18        13:30            8.0         125
47        15:30            8.5         123
8         12:00            9.0         116
76        17:30            6.5         112
70        17:00            7.0         111
64        16:30            7.5          86
37        15:00            9.0          78
3         11:30            9.0          76
48        15:30            9.0          74
31        15:00            6.0          74
56        16:00            8.0          73
79        17:30            8.0          67
82        18:00            6.0          59
86        18:00            8.0          45
92        18:30            7.5          36
10        12:30            8.0          34
23        14:00            7.5          32
67        16:30            9.0          31
72        17:00            8.0          31
12        12:30            9.0          25
35        15:00            8.0          23
85        18:00            7.5          20
46        15:30            8.0          20
33        15:00            7.0          20
58        16:00            9.0          19
51        15:30           10.5          18
89        18:30            5.5          18
65        16:30            8.0          17
80        17:30            8.5          15
   entrada_norm  duracion_norm  frecuencia  acumulado
11        12:30            8.5         181   0.089471
18        13:30            8.0         125   0.151261
47        15:30            8.5         123   0.212061
8         12:00            9.0         116   0.269402
76        17:30            6.5         112   0.324765
70        17:00            7.0         111   0.379634
64        16:30            7.5          86   0.422145
37        15:00            9.0          78   0.460702
3         11:30            9.0          76   0.498270
48        15:30            9.0          74   0.534849
31        15:00            6.0          74   0.571429
56        16:00            8.0          73   0.607514
79        17:30            8.0          67   0.640633
82        18:00            6.0          59   0.669797
86        18:00            8.0          45   0.692042
92        18:30            7.5          36   0.709837
10        12:30            8.0          34   0.726644
23        14:00            7.5          32   0.742462
67        16:30            9.0          31   0.757785
72        17:00            8.0          31   0.773109
12        12:30            9.0          25   0.785467
35        15:00            8.0          23   0.796836
85        18:00            7.5          20   0.806723
46        15:30            8.0          20   0.816609
33        15:00            7.0          20   0.826495
58        16:00            9.0          19   0.835887
51        15:30           10.5          18   0.844785
89        18:30            5.5          18   0.853683
65        16:30            8.0          17   0.862086
80        17:30            8.5          15   0.869501

In [13]:
# Análisis trabajadores concretos

tabla = pd.crosstab(
    df_horarios["worker_id"],
    df_horarios["entrada_norm"]
)

print(tabla)

entrada_norm  10:00  11:30  12:00  12:30  13:00  13:30  14:00  14:30  15:00  \
worker_id
0                 0      6     30     54      1     14      7      0     13
1                 1     18     26     76      1      9      1      1     21
2                 0      0      0      7      3      1      0      0      0
3                 0      0      0      5      1      0      0      0      2
4                 0      0      3      5      0      7      0      0      2
5                 0      2      0     12      1      8      6      0      5
6                 0      0      0      5      1      0      0      0      1
7                 0      0      0      0      2      1      0      0      2
8                 0     21     21      7      2     15      8      0     25
9                 0      0      3     10      1      9      0      0      3
10                0      0      0      0      0      2      0      0      4
11                0      0      0     22      0      3      0      0      3
12                0      0      0      0      0      2      0      0      0
13                0      0      0      0      0      1      0      0      6
14                0      1      1      2      0      0      0      0     30
15                0      0      0      1      0      2      7      1      6
16                0      3     14     36      1     12      5      0     13
17                0      0      0      0      0      5      3      0      1
18                0     21     19      0      0     19      6      0     20
19                0      0      0      0      0      8      1      0     10
20                0      0      0      0      0      3      0      0      2
21                0      0      0      0      0      4      1      0      3
22                1     12     13      0      0     13     13      0     26
23                0      0      0      0      0      0      0      0      2
24                0      0      0      0      0      2      0      0      5
25                0      0      0      0      0      0      0      1      2
26                0      0      1      0      0      2      2      0      4
27                0      0      0      0      0      1      0      0      3
28                0      0      0      0      0      0      0      0      1

entrada_norm  15:30  16:00  16:30  17:00  17:30  18:00  18:30  19:00
worker_id
0                25     11     32     26     37     24     21      0
1                23      9     19     21     32     30     10      3
2                 2      0      0      1      1      1      3      0
3                 0      1      0      0      1      2      1      0
4                 3      1      2      1      5      0      3      1
5                15      2      3      8      6      4      1      0
6                 1      0      1      3      4      2      1      0
7                 1      0      0      3      2      2      1      0
8                30     16     12     17     30     11      6      2
9                 1      0      1      2      0      0      0      0
10                2      0      2      0      0      2      0      0
11                4      3      5      5      7      3      0      0
12                2      0      1      3      3      1      0      0
13                3      0      0      0      0      0      0      0
14               31     21      9      3      7      1      0      0
15                9      4      6      7      3      2      0      0
16               19     12     11     13     18      7     10      1
17                7      1      6      5      3      1      1      0
18               24     18     16     15     17     15      7      0
19                3      5      1      4      6      6      0      0
20                1      1      2      8      5      5      2      0
21                0      5      1      3      9      2      0      0
22               32      5     10     14     10      9      2      0
23                6      0      0      0      3      2      1      0
24               13      1      3      3      4      0      1      0
25                3      0      1      0      0      0      0      0
26                6      2      1      1      0      1      0      0
27                3      1      1      0      1      0      0      0
28                2      0      1      1      0      0      0      0

In [14]:
# Fecha
df_horarios["fecha"] = pd.to_datetime(
    df_horarios["fecha"]
)

# Hora de entrada
df_horarios["entrada"] = pd.to_datetime(
    df_horarios["entrada"],
    errors="coerce"
)

# ----------------------------------------
# EXPANDIR TURNOS A BLOQUES DE 30 MINUTOS
# ----------------------------------------

registros = []

for _, row in df_horarios.iterrows():

    fecha = row["fecha"]

    inicio = pd.to_datetime(
    row["entrada_norm"],
    format="%H:%M"
)
    fin = inicio + pd.to_timedelta(
        row["duracion_norm"],
        unit="h"
    )

    instante = inicio

    while instante < fin:

        registros.append(
            {
                "fecha": fecha,
                "hora": instante.strftime("%H:%M")
            }
        )

        instante += timedelta(minutes=30)

cobertura = pd.DataFrame(registros)

# ----------------------------------------
# PERSONAS POR FECHA Y MEDIA HORA
# ----------------------------------------

cobertura_real = (
    cobertura
    .groupby(
        ["fecha", "hora"]
    )
    .size()
    .reset_index(name="personas")
)

print("\nCOBERTURA REAL")
print(cobertura_real.head(50))

# ----------------------------------------
# DIA SEMANA
# ----------------------------------------

cobertura_real["dia_semana"] = (
    cobertura_real["fecha"]
    .dt.day_name()
)

cobertura_media = (
    cobertura_real
    .groupby(["dia_semana", "hora"])["personas"]
    .mean()
    .reset_index()
)

# Orden correcto de días
orden = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

cobertura_media["dia_semana"] = pd.Categorical(
    cobertura_media["dia_semana"],
    categories=orden,
    ordered=True
)

cobertura_media = cobertura_media.sort_values(
    ["dia_semana", "hora"]
)

print("\nCOBERTURA MEDIA")
print(cobertura_media.head(200))

# =========================
# TABLA PIVOT MUY ÚTIL
# =========================

pivot = cobertura_media.pivot(
    index="hora",
    columns="dia_semana",
    values="personas"
)

print("\nPIVOT COBERTURA")
print(pivot.round(2))

COBERTURA REAL
        fecha   hora  personas
0  2024-08-05  00:00         2
1  2024-08-05  00:30         2
2  2024-08-05  01:00         2
3  2024-08-05  01:30         2
4  2024-08-05  12:30         2
5  2024-08-05  13:00         3
6  2024-08-05  13:30         3
7  2024-08-05  14:00         3
8  2024-08-05  14:30         3
9  2024-08-05  15:00         3
10 2024-08-05  15:30         3
11 2024-08-05  16:00         3
12 2024-08-05  16:30         3
13 2024-08-05  17:00         3
14 2024-08-05  17:30         3
15 2024-08-05  18:00         4
16 2024-08-05  18:30         5
17 2024-08-05  19:00         5
18 2024-08-05  19:30         5
19 2024-08-05  20:00         5
20 2024-08-05  20:30         4
21 2024-08-05  21:00         3
22 2024-08-05  21:30         2
23 2024-08-05  22:00         2
24 2024-08-05  22:30         2
25 2024-08-05  23:00         2
26 2024-08-05  23:30         2
27 2024-08-06  00:00         2
28 2024-08-06  00:30         2
29 2024-08-06  01:00         2
30 2024-08-06  01:30         2
31 2024-08-06  12:30         2
32 2024-08-06  13:00         3
33 2024-08-06  13:30         3
34 2024-08-06  14:00         3
35 2024-08-06  14:30         3
36 2024-08-06  15:00         3
37 2024-08-06  15:30         3
38 2024-08-06  16:00         3
39 2024-08-06  16:30         3
40 2024-08-06  17:00         3
41 2024-08-06  17:30         3
42 2024-08-06  18:00         4
43 2024-08-06  18:30         5
44 2024-08-06  19:00         5
45 2024-08-06  19:30         5
46 2024-08-06  20:00         5
47 2024-08-06  20:30         4
48 2024-08-06  21:00         3
49 2024-08-06  21:30         2

COBERTURA MEDIA
    dia_semana   hora  personas
29      Monday  00:00  2.666667
30      Monday  00:30  2.700000
31      Monday  01:00  2.400000
32      Monday  01:30  2.111111
33      Monday  12:00  1.000000
..         ...    ...       ...
105     Sunday  19:30  5.478873
106     Sunday  20:00  5.464789
107     Sunday  20:30  5.267606
108     Sunday  21:00  3.802817
109     Sunday  21:30  2.845070

[200 rows x 3 columns]

PIVOT COBERTURA
dia_semana  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday  Sunday
hora
00:00         2.67     2.25       2.67      2.46    2.26      2.79    3.00
00:30         2.70     2.44       2.70      2.78    2.27      2.32    3.17
01:00         2.40     2.50       2.78      2.56    2.00      1.95    2.50
01:30         2.11     2.14       2.57      2.43    2.33      2.67    1.90
10:00          NaN     2.00        NaN       NaN     NaN       NaN     NaN
10:30          NaN     2.00        NaN       NaN     NaN       NaN     NaN
11:00          NaN     2.00        NaN       NaN     NaN       NaN     NaN
11:30          NaN     1.08       1.00      1.05    1.00       NaN    1.00
12:00         1.00     1.05       1.00      1.03    1.00      1.00    1.03
12:30         1.02     1.05       1.05      1.10    1.06      1.09    1.10
13:00         1.03     1.11       1.06      1.11    1.09      1.10    1.14
13:30         1.24     1.24       1.19      1.26    1.27      1.54    1.92
14:00         1.30     1.26       1.21      1.26    1.37      2.00    2.08
14:30         1.30     1.26       1.21      1.26    1.37      2.03    2.10
15:00         1.73     1.68       1.56      1.73    1.73      2.34    2.96
15:30         2.19     2.21       2.06      2.17    2.28      3.01    3.69
16:00         2.35     2.29       2.21      2.34    2.55      3.31    4.30
16:30         2.57     2.36       2.41      2.59    2.94      3.90    4.63
17:00         2.91     2.64       2.64      2.89    3.37      4.46    4.97
17:30         3.18     3.10       3.06      3.20    4.07      5.20    5.21
18:00         3.38     3.31       3.26      3.47    4.66      5.49    5.39
18:30         3.51     3.46       3.36      3.57    5.01      5.65    5.48
19:00         3.53     3.49       3.36      3.59    5.06      5.66    5.48
19:30         3.53     3.49       3.36      3.59    5.06      5.66    5.48
20:00         3.53     3.49       3.36      3.59    5.06      5.63    5.46
20:30         3.44     3.10       3.07      3.23    4.65      5.55    5.27
21:00         2.49     2.44       2.46      2.60    3.87      4.44    3.80
21:30         2.24     2.28       2.26      2.34    3.45      3.70    2.85
22:00         2.22     2.30       2.23      2.30    3.39      3.66    2.56
22:30         2.22     2.30       2.20      2.30    3.39      3.62    2.51
23:00         2.16     2.22       2.16      2.23    3.34      3.54    2.37
23:30         2.09     2.14       2.14      2.16    3.32      3.32    2.26